name: make the fucking package json

on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Generate package.json and lock
        run: |
          npm init -y
          npm install --package-lock-only

      - name: Commit and push package files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Make sure we're on main, not detached
          git checkout main

          git add package.json package-lock.json
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: add or update package.json and package-lock.json from ${GITHUB_SHA}"
            git push origin HEAD:main
          fi
